server:
    port: ${SERVER_PORT:8080}
    session-timeout: ${SESSION_TIMEOUT:60}
keystore:
    file : src/main/resources/private/keystorejks
    pass : password
backend:
    admin:
        username: ${BACKEND_USERNAME:admin}
        password: ${BACKEND_PASSWORD:admin}
        role: BACKEND_ADMIN
aws.accessKey : ${AWS_ACCESS_KEY:AKIAJ7RYJ77B4MYI7FWA}
aws.secreetKey : ${AWS_SECREET_KEY:LVZk2CdRUn2qJ3tcxaGG9zkj5rNx8P4QEKrU0R7d}

logging.level.org.springframework.web : TRACE
security.basic.enabled : false
endpoints.shutdown.enabled : true
spring.thymeleaf.mode : LEGACYHTML5